name: Maven Snapshot

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: install apt dependencies
        shell: bash
        run: sudo apt-get install -y xmlstarlet
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: 'maven'

      - name: Build with Maven
        shell: bash
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        shell: bash
        run: mvn deploy -DuseGithubRepository=true -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
